HistClinica/HistClinica/Controllers/PacienteController.cs
using HistClinica.DTO;
using HistClinica.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace HistClinica.Controllers
{
    public class PacienteController : Controller
    {
        private readonly IPersonaRepository _personaRepository;
        private readonly IPacienteRepository _pacienteRepository;
        private readonly IUtilRepository _utilrepository;
        private readonly ICitaRepository _citarepository;

        public PacienteController(IPersonaRepository personaRepository, IPacienteRepository pacienteRepository, IUtilRepository utilrepository, ICitaRepository citaRepository)
        {
            _personaRepository = personaRepository;
            _pacienteRepository = pacienteRepository;
            _utilrepository = utilrepository;
            _citarepository = citaRepository;
        }


        public async Task<IActionResult> Index()
        {
            if (TempData.ContainsKey("mensajecita"))
            {
                ViewBag.message = TempData["mensajecita"].ToString();
            }
            if (TempData.ContainsKey("dni"))
            {
                var dni = TempData["dni"].ToString();
                PersonaDTO personaDTO = await _pacienteRepository.GetByDnioNombresyApellidos(Convert.ToInt32(dni), "", "");
                return View(personaDTO);
            }
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Index(int dni, string nombre, string apellidos)
        {
            PersonaDTO personaDTO = await _pacienteRepository.GetByDnioNombresyApellidos(dni, nombre, apellidos);
            return View(personaDTO);
        }

        public async Task<IActionResult> AdmicionMedico()
        {
            if (TempData.ContainsKey("msjcita"))
            {
                ViewBag.message = TempData["msjcita"].ToString();
            }
            List<CitaDTO> cita = await _citarepository.GetAllCitas();
            return View(cita);
        }

        // GET: Paciente/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _pacienteRepository.GetByDnioNombresyApellidos(id, "", "");
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        private async Task CargarCombosPacientes()
        {
            var lsttipsexo = new Object();
            lsttipsexo = await _utilrepository.GetTipo("sexo");
            ViewBag.lssexo = lsttipsexo;

            var lsgrdinstruccion = new Object();
            lsgrdinstruccion = await _utilrepository.GetTipo("grado instruccion");
            ViewBag.lgrdinst = lsgrdinstruccion;

            var ocupacion = new Object();
            ocupacion = await _utilrepository.GetTipo("Ocupacion");
            ViewBag.locupacion = ocupacion;

            var gruposangre = new Object();
            gruposangre = await _utilrepository.GetTipo("Grupo Sangre");
            ViewBag.lgpsangre = gruposangre;

            var factrh = new Object();
            factrh = await _utilrepository.GetTipo("Factor RH");
            ViewBag.lfh = factrh;

            var parentesco = new Object();
            parentesco = await _utilrepository.GetTipo("Parentesco");
            ViewBag.lparentesco = parentesco;

            var tipovia = new Object();
            tipovia = await _utilrepository.GetTipo("Tipo Via");
            ViewBag.ltipovia = tipovia;

            var tippac = new Object();
            tippac = await _utilrepository.GetTipo("Tipo Paciente");
            ViewBag.ltippac = tippac;

            var estadocivil = new Object();
            estadocivil = await _utilrepository.GetTipo("Estado Civil");
            ViewBag.lestcivil = estadocivil;

            var tipdoc = new Object();
            tipdoc = await _utilrepository.GetTipo("Tipo Documento");
            ViewBag.ltipdoc = tipdoc;
        }

        // GET: Paciente/Create
        public async Task<IActionResult> Create()
        {
            await CargarCombosPacientes();
            return View();
        }

        // POST: Paciente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonaDTO persona)
        {
            if (persona != null)
            {
                TempData["dni"] = persona.numeroDocumento;
                TempData["mensajecita"] = await _personaRepository.InsertPersona(persona);
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Paciente/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await CargarCombosPacientes();
            PersonaDTO persona = await _pacienteRepository.GetById(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Paciente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PersonaDTO persona)
        {

            if (persona != null)
            {
                try
                {
                    TempData["dni"] = persona.numeroDocumento;
                    TempData["mensajecita"] = await _personaRepository.UpdatePersona(persona);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _pacienteRepository.PacienteExists(persona.paciente.idPaciente)))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Paciente/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _pacienteRepository.GetByDnioNombresyApellidos(id, "", "");
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        // POST: Paciente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paciente = await _pacienteRepository.GetByDnioNombresyApellidos(id, "", "");
            await _pacienteRepository.DeletePaciente(id);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Pago()
        {
            return View();
        }

    }
}

HistClinica/HistClinica/Views/Paciente/AdmicionMedico.cshtml
@model List<HistClinica.DTO.CitaDTO>

@{
	ViewBag.Title = "ProgramarCitaAdmision";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

	<div class="container">
		<div class="row">
			<div class="col-sm-12 text-center">
				<div class="card card-primary">
					<div class="card-header">
						<h1>Listado de citas</h1>
					</div>
				</div>

			</div>
		</div>
		@*
		<div class="row" style="padding-top:20px;">
			<div class="col-sm-12 pb-3">
				<span style="font-size: 18px;">Buscar por:</span>
				<div class="pl-3 form-check form-check-inline">
					<input class="form-check-input" type="radio" checked name="radiofiltro" id="inlineRadio1" value="1">
					<label class="form-check-label" for="inlineRadio1">Por Dni</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="radiofiltro" id="inlineRadio2" value="2">
					<label class="form-check-label" for="inlineRadio2">Por Nombre y apellido</label>
				</div>
			</div>
			<div class="col-sm-12">
				@using (Html.BeginForm())
				{
				<div class="row">
					<div class="col-sm-2">
						<select class="form-control">
							<option value="value">DNI</option>
						</select>
					</div>
					<div class="col-sm-2">
						<input type="text" id="dni" name="dni" class="form-control" />
					</div>
					<div class="col-sm-2">
						<input type="text" id="nombre" name="nombre" class="form-control" placeholder="Ingrese nombre" />
					</div>
					<div class="col-sm-2">
						<input type="text" id="apellidos" name="apellidos" class="form-control" placeholder="Ingrese apellidos" />
					</div>
						<div class="col-sm-4">
			<button class="btn btn-info" type="submit" id="btnBuscar"><i class="fas fa-search"></i></button>
			<a class="btn btn-primary" type="submit" asp-action="Create" asp-controller="Paciente"><i class="fas fa-user-plus"></i></a>
			<button class="btn btn-secondary" type="submit" onclick="return getbyID();"><i class="fas fa-edit"></i></button>
		</div>
				</div>
				}
			</div>
		</div>
		*@
		@if (ViewBag.message != null)
		{
			<div class="col-sm-12 alert alert-info alert-dismissible text-center" role="alert" style="margin-top: 15px;">
				<button type="button" class="close" data-dismiss="alert" aria-label="close">
					<span aria-hidden="true">&times;</span>
				</button>
				@ViewBag.message
			</div>
		}
		<div class="row" style="padding-top: 80px;">
			<div class="col-sm-12">
				<table class="table table-bordered table-responsive table-hover" style="font-size:14px;" id="citamedicogrid">
					<thead>
						<tr>
							<th>#</th>
							<th>N°</th>
							<th>Tipo</th>
							<th>Paciente</th>
							<th>Fecha</th>
							<th>Hora</th>
							<th>Producto</th>
							<th>Descripción</th>
							<th>Medico</th>
							<th>Especialidad</th>
							<th>Estado</th>
							<th>Est.Pago</th>
							<th>Total</th>
							<th>Acciones</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
								{
						<tr>
							<td>@item.idCita</td>
							<td>@item.nroCita</td>
							<td>@item.TipoCita</td>
							<td nowrap>@item.nombrePaciente</td>
							<td nowrap>@item.fecha</td>
							<td>@item.hora</td>
							<td>@item.consultorio</td>
							<td>@item.descripcion</td>
							<td nowrap>@item.medico</td>
							<td>@item.especialidad </td>
							<td>@item.descEstado</td>
							<td>@item.descEstadoPago</td>
							<td>@item.precio</td>
							<td>
								<button title="Editar" class="edit btn btn-primary"><i class="fas fa-address-book"></i></button>
							</td>
						</tr>
								}
					</tbody>
				</table>
			</div>
		</div>
	</div>



<div id="modalcambiarestado" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
</div>

<script src="~/js/cargavistaparcial.js"></script>

HistClinica/HistClinica/Views/Paciente/Index.cshtml
@model HistClinica.DTO.PersonaDTO

@{ ViewBag.Title = "ProgramarCitaAdmision";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="container">
    <div class="row">
        <div class="col-sm-12 text-center">
            <div class="card card-primary">
                <div class="card-header">
                    <h1>Admision</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="padding-top:20px;">
        <div class="col-sm-12 pb-3">
            <span style="font-size: 18px;">Buscar por:</span>
            <div class="pl-3 form-check form-check-inline">
                <input class="form-check-input" type="radio" checked name="radiofiltro" id="inlineRadio1" value="1">
                <label class="form-check-label" for="inlineRadio1">Por Dni</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="radiofiltro" id="inlineRadio2" value="2">
                <label class="form-check-label" for="inlineRadio2">Por Nombre y apellido</label>
            </div>
        </div>
        <div class="col-sm-12">
            @using (Html.BeginForm())
            {
<div class="row">
    @Html.HiddenFor(m => m.paciente.idPaciente)
    <div class="col-sm-2">
        <select class="form-control">
            <option value="value">DNI</option>
        </select>
    </div>
    <div class="col-sm-2">
        <input type="text" id="dni" name="dni" class="form-control" />
    </div>
    <div class="col-sm-2">
        <input type="text" id="nombre" name="nombre" class="form-control" placeholder="Ingrese nombre" />
    </div>
    <div class="col-sm-2">
        <input type="text" id="apellidos" name="apellidos" class="form-control" placeholder="Ingrese apellidos" />
    </div>
    <div class="col-sm-4">
        <button class="btn btn-info" type="submit" id="btnBuscar"><i class="fas fa-search"></i></button>
        <a class="btn btn-primary" type="submit" asp-action="Create" asp-controller="Paciente"><i class="fas fa-user-plus"></i></a>
        @if (Model != null)
        {
<a class="btn btn-secondary" type="submit" asp-action="Edit" asp-controller="Paciente" asp-route-id="@Model.paciente.idPaciente"><i class="fas fa-edit"></i></a>}
    </div>
</div>}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="row pt-3">
                <div class="col-sm-4">
                    <label>Paciente</label>
                </div>
                <div class="col-sm-8">
                    <div class="divpac">
                        <label>@Html.DisplayFor(m => m.apellidoPaterno) @Html.DisplayFor(m => m.apellidoMaterno) @Html.DisplayFor(m => m.nombres) </label>
                    </div>
                </div>
            </div>
            <div class="row" style="padding-top: 10px;">
                <div class="col-sm-4">
                    <label>DNI</label>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.numeroDocumento, new { @class = "form-control", @disabled = "true" })
                </div>
            </div>
            <div class="row" style="padding-top: 10px;">
                <div class="col-sm-4">
                    <label>Correo</label>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.correo, new { @class = "form-control", @disabled = "true" })
                </div>
            </div>
            <div class="row" style="padding-top: 10px;">
                <div class="col-sm-4">
                    <label>Edad</label>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.edad, new { @class = "form-control", @disabled = "true" })
                </div>
            </div>
            <div class="row pb-2" style="padding-top: 10px;">
                <div class="col-sm-4">
                    <label>Ocupación</label>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.descripcionOcupacion, new { @class = "form-control", @disabled = "true" })
                </div>
            </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">

        </div>
    </div>
    <div class="row" style="padding-top: 10px;">
        <div class="col-sm-12">
            <button style="width: 112px; font-size: 15px;" class="btn btn-primary" onclick="CargaModalCitas();">Citas</button>
            <button style="width: 135px; font-size: 15px;" class="btn btn-primary">Orden</button>
            <button onclick="CargaConsultaCronograma();" style="width: 135px; font-size: 15px;" class="btn btn-primary">Cronograma</button>
        </div>
    </div>
    @if (ViewBag.message != null)
    {
<div class="col-sm-12 alert alert-info alert-dismissible text-center" id="success-alert" role="alert" style="margin-top: 15px;">
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">&times;</span>
    </button>
    @ViewBag.message
</div>}
    <div class="row" style="padding-top: 80px;">
        <div class="col-sm-12">
            <table class="table table-bordered table-responsive table-hover" style="font-size:14px;" id="citagrid">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>N°</th>
                        <th>Tipo</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th>Producto</th>
                        <th>Descripción</th>
                        <th>Medico</th>
                        <th>Especialidad</th>
                        <th>Precio</th>
                        <th>IGV</th>
                        <th>Estado</th>
                        <th>Est.Pago</th>
                        <th>Total</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @{ if (Model != null)
                                    {
                                        foreach (var item in Model.paciente.cita)
                                        {
                        <tr>
                            <td>@item.idCita</td>
                            <td>@item.nroCita</td>
                            <td>@item.TipoCita</td>
                            <td nowrap>@item.fecha</td>
                            <td>@item.hora</td>
                            <td>@item.consultorio</td>
                            <td>@item.descripcion</td>
                            <td nowrap>@item.medico</td>
                            <td>@item.especialidad </td>
                            <td nowrap>@item.precio</td>
                            <td nowrap>@item.igv</td>
                            <td>@item.descEstado</td>
                            <td>@item.descEstadoPago</td>
                            <td>@item.precio</td>
                            <td nowrap>
                                <button title="Reprogramar" class="edit btn btn-primary"><i class="fas fa-address-book"></i></button>
                                <button title="Consultar" class="detail btn btn-primary">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                                <button title="Anular" class="anular btn btn-danger">
                                    <i class="fa fa-minus" aria-hidden="true"></i>
                                </button>
                            </td>
                        </tr> }
                                    } }
                </tbody>
            </table>
        </div>
        <div class="col-sm-12 text-right">
            <span style="margin-right:10px;">TOTAL DE VALOR VENTA - OPERACION GRAVADA</span><span>300</span><br />
            <span style="margin-right:10px;">IGV(18%)</span><span>54</span><br />
            <span style="margin-right:10px;">IMPORTE TOTAL</span><span>354</span>
        </div>
        <div class="col-sm-12" style="padding-top: 10px;">
            <div class="row">
                <div class="col-sm-6">

                </div>
                <div class="col-sm-6 text-right">
                    <a asp-action="Pago" asp-controller="Paciente" class="btn btn-primary" style="width: 112px;font-size: 16px;">Pagar</a>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="modalcitas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>
<div class="modal fade" id="modalreprogramar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>

<div id="modalcronograma" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
</div>
<div id="modaldetallecro" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
</div>
<div id="modalanular" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
</div>
<div id="modaldetalle" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
</div>
<script src="~/js/cargavistaparcial.js"></script>
<script src="~/js/combosaninadoscitas.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HistClinica/HistClinica/Views/Paciente/Pago.cshtml
@{
	ViewData["Title"] = "Pago";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

	<div class="container">
		<div class="col-sm-12 text-center pt-2 pb-4">
			<div class="card card-primary">
				<div class="card-header">
					<h1>Paga Online de forma segura con tu tarjeta de credito o debito</h1>
				</div>
			</div>
		</div>

		<div align="center">
			<div align='left'>
				<font color="gray"><h1>Ingresa los datos de tu tarjeta de credito o debito</h1></font>
			</div>
			<h4></h4>

			<h4></h4>


			<form action="#" class="credit-card-div">
				<div class="panel panel-default">
					<div class="panel-heading">

						<div class="row ">
							<div class="col-md-4">
								<input type="text" class="form-control" placeholder="Ingrese el Numero de Tarjeta" />
							</div>
						</div>
						<h4></h4>

						<div class="row ">


							<div class="col-md-1 col-sm-1 col-xs-1">
								<span class="help-block text-muted small-font"> Mes de Vencimiento</span>
								<input type="text" class="form-control" placeholder="MM" />
							</div>
							<div class="col-md-1 col-sm-1 col-xs-1">
								<span class="help-block text-muted small-font">  Año de Vencimiento</span>
								<input type="text" class="form-control" placeholder="YY" />
							</div>

							<div class="col-md-1 col-sm-1 col-xs-1">
								<span class="help-block text-muted small-font">  Año de Vencimiento</span>
								<input type="text" class="form-control" placeholder="CCV" />
							</div>
						</div>

						<h4></h4>

						<div class="row ">
							<div class="col-md-4 pad-adjust">

								<input type="text" class="form-control" placeholder="Nombre en la Tarjeta" />
							</div>
						</div>

						<h4></h4>
						<h4></h4>
						<div class="row" align="left">
							<div class="col-md-12 pad-adjust">
								<div class="checkbox">
									<label>
										<input type="checkbox" checked class="text-muted"> Guardar detalles para pagos rápidos.<a href="#"> ¿cómo?</a>
									</label>
								</div>
							</div>
						</div>
						<div align="left">

							<a class="btn btn-primary" asp-action="Agregar" asp-controller="Detalle">
								Pagar
							</a>

							<a class="btn btn-danger" asp-action="Index" asp-controller="Paciente" align="right">
								Cerrar
							</a>
						</div>

					</div>
				</div>
			</form>

		</div>
	</div>