HistClinica/HistClinica/Controllers/CronogramaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HistClinica.Data;
using HistClinica.DTO;
using HistClinica.Models;
using HistClinica.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HistClinica.Controllers
{
    public class CronogramaController : Controller
    {
        private readonly ClinicaServiceContext _context;
        private readonly ICronogramaRepository cronogramaRepository;
        private readonly IUtilRepository _utilrepository;

        public CronogramaController(ClinicaServiceContext clinicaService, ICronogramaRepository cronograma, IUtilRepository utilRepository)
        {
            _context = clinicaService;
            cronogramaRepository = cronograma;
            _utilrepository = utilRepository;
        }


        public async Task<IActionResult> Index()
        {

            string[] horas = new string[] {"1:00","2:00","3:00","4:00","5:00","6:00","7:00","8:00","9:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24:00"};


            //combo consultorios
            var lconsultorio =  await _utilrepository.GetTipo("Consultorio");
            ViewBag.listaconsultorio = lconsultorio;

            //combo especialidades
            var lespecialidads = await _utilrepository.GetTipo("Especialidad");
            ViewBag.listaespecialidades = lespecialidads;

            //combo horas
            ViewBag.listahoras = horas;

            //combo medicos
            var medico = await _utilrepository.GetMedicos();
            ViewBag.listamedicos = medico;

            //listar
            List<CronogramaDTO> cronograma = new List<CronogramaDTO>();
            cronograma = await cronogramaRepository.GetAllCronogramas();

            if (TempData["mensaje"] != null)
            {
                ViewBag.message = TempData["mensaje"].ToString();
            }

            return View(cronograma);
        }

        public async Task<JsonResult> GetEspecialidad(int id)
        {
            var newlistespe = await _utilrepository.GetEspecialidad(id);
           // ViewBag.listaespecialidades = newlistespe;
            return Json(newlistespe);
        }

        public async Task<IActionResult> Create(D012_CRONOMEDICO cronoMedico)
        {
            if (cronoMedico != null)
            {
               TempData["mensaje"] = await cronogramaRepository.InsertCronograma(cronoMedico);
               return RedirectToAction("Index");
            }
            return PartialView();
        }

        public async Task<IActionResult> Delete(int id)
        {

            CronogramaDTO cronograma = await cronogramaRepository.GetByIdCrono(id);
            return PartialView(cronograma);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(D012_CRONOMEDICO cronograma)
        {

            await cronogramaRepository.DeleteCronograma(cronograma.idProgramMedica);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int id)
        {

            CronogramaDTO cronoMedico = await cronogramaRepository.GetByIdCrono(id);

            return PartialView(cronoMedico);
        }

        public async Task<IActionResult> Editar(int id)
        {
            string[] horas = new string[] { "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", "24:00" };

            //combo consultorios
            var lconsultorio = await _utilrepository.GetTipo("Consultorio");
            ViewBag.listaconsultorio = lconsultorio;

            //combo especialidades
            var lespecialidads = await _utilrepository.GetTipo("Especialidad");
            ViewBag.listaespecialidades = lespecialidads;

            //combo estado
            var estado = new Object();
            estado = await _utilrepository.GetTipo("ESTADO CRONOGRAMA");
            ViewBag.lestado = estado;

            //combo medicos
            var medico = await _utilrepository.GetMedicos();
            ViewBag.listamedicos = medico;

            ViewBag.listahoras = horas;

            CronogramaDTO cronoMedico = await cronogramaRepository.GetByIdCrono(id);

            return PartialView("Edit",cronoMedico);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(D012_CRONOMEDICO cronoMedico)
        {
            if (ModelState.IsValid)
            {
                TempData["mensaje"] = await cronogramaRepository.UpdateCronograma(cronoMedico);
                return RedirectToAction("Index");
            }
            return PartialView();
        }

        [HttpGet]
        public async Task<IActionResult> ConsultarCronograma()
        {
            List<CronogramaDTO> cronograma = new List<CronogramaDTO>();
            cronograma = await cronogramaRepository.GetAllCronogramasConsulta();

            //filtro de medico
            var medico = await _utilrepository.GetMedicos();
            ViewBag.listamedicos = medico;

            return PartialView(cronograma);
        }
        
        public async Task<IActionResult> ConsultarCronogramapost(int id)
        {
            var medico = await _utilrepository.GetMedicos();
            ViewBag.listamedicos = medico;

            List<CronogramaDTO> cronograma = new List<CronogramaDTO>();
            cronograma = await cronogramaRepository.GetCronogramaByMedico(id);
            return PartialView("ConsultarCronograma", cronograma);
        }
    }
}

HistClinica/HistClinica/Views/Cronograma/ConsultarCronograma.cshtml
@model IEnumerable<HistClinica.DTO.CronogramaDTO>

<div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h2 class="modal-title text-center" id="exampleModalLabel1">Consultar cronograma</h2>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		<div class="container">
			<div class="col-sm-12 pt-3">


				@using (Html.BeginForm())
				{
					<div class="row pb-2">
						<div class="col-sm-4">
							<div class="row">
								<div class="col-sm-4">
									<label>Medico</label>
								</div>

								<div class="col-sm-8">
									@Html.DropDownList("idmedico", new SelectList(ViewBag.listamedicos, "idMedico", "nombres"), "Seleccione", new { @class = "form-control" })
								</div>
							</div>
						</div>
						<div class="col-sm-4">
						</div>
						<div class="col-sm-4">

						</div>
					</div>
				}

				<div class="row pt-3">
					<div class="col-sm-12">
						<table class="table table-bordered table-hover text-center" id="consultacronogrid">
							<thead>
								<tr>
									<th>Id</th>
									<th>Medico</th>
									<th>Fecha Ini</th>
									<th>Fecha Fin</th>
									<th>Hora ini</th>
									<th>Hora fin</th>
									<th>Estado</th>
								</tr>
							</thead>
							<tbody>
								@foreach (var item in Model)
								{
								<tr>
									<td>@item.idProgramMedica</td>
									<td>@item.medico</td>
									<td>@item.fechaIni</td>
									<td>@item.fechaFin</td>
									<td>@item.hrInicio</td>
									<td>@item.hrFin</td>
									<td>@item.desEstado</td>
								</tr>
								}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

HistClinica/HistClinica/Views/Cronograma/Create.cshtml
@model HistClinica.Models.D012_CRONOMEDICO

@using (Html.BeginForm("Create", "Cronograma", FormMethod.Post, new { @id = "frmcrearcronograma" }))
{
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="row pb-2">
		<div class="col-sm-4">
			<div class="row">
				<div class="col-sm-4">
					<label>Medico</label>
				</div>
				<div class="col-sm-8">
					@Html.DropDownListFor(m => m.idMedico, new SelectList(ViewBag.listamedicos, "idMedico", "nombres"), "Seleccione", new
					{
						@class = "form-control",
				   data_cascade_combo = "#stypes",
				   data_cascade_combo_source = Url.Action("GetEspecialidad", "Cronograma"),
				   data_cascade_combo_param_name = "id"
			   })
					@Html.ValidationMessageFor(model => model.idMedico, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="row">
				<div class="col-sm-4">
					<label>Especialidad</label>
				</div>
				<div class="col-sm-8">
					@Html.DropDownListFor(m => m.idEspecialidad, new SelectList(ViewBag.listaespecialidades, "idtab", "descripcion"), "Seleccione", new { @class = "form-control", id = "stypes" })
					@Html.ValidationMessageFor(model => model.idEspecialidad, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="row">
				<div class="col-sm-4">
					<label>Consultorio</label>
				</div>
				<div class="col-sm-8">
					@Html.DropDownListFor(m => m.idConsultorio, new SelectList(ViewBag.listaconsultorio, "idtab", "descripcion"), "Seleccione", new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.idConsultorio, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
	</div>
	<div class="row pb-2">
		<div class="col-sm-4">
			<div class="row">
				<div class="col-sm-4">
					<label>Fecha Inicio</label>
				</div>
				<div class="col-sm-8">
					@Html.TextBoxFor(m => m.fechaIni, new { @class = "form-control", @type = "Date" })
					@Html.ValidationMessageFor(model => model.fechaIni, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="row">
				<div class="col-sm-4">
					<label>Fecha Fin</label>
				</div>
				<div class="col-sm-8">
					@Html.TextBoxFor(m => m.fechaFin, new { @class = "form-control", @type = "Date" })
					@Html.ValidationMessageFor(model => model.fechaFin, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<div class="row">
				<div class="col-sm-4">
					<label>Hora Inicio</label>
				</div>
				<div class="col-sm-8">
					@Html.DropDownListFor(m => m.hrInicio, new SelectList(ViewBag.listahoras), "Seleccione", new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.hrInicio, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
		<div class="col-sm-4 pt-2">
			<div class="row">
				<div class="col-sm-4">
					<label>Hora Fin</label>
				</div>
				<div class="col-sm-8">
					@Html.DropDownListFor(m => m.hrFin, new SelectList(ViewBag.listahoras), "Seleccione", new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.hrFin, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>
	</div>
	<div class="row pb-2 text-right">
		<div class="col-sm-12">
			<button class="btn btn-primary" id="Crear">Guardar</button>
		</div>
	</div>
}
<script src="~/js/comboaninado.js"></script>
@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HistClinica/HistClinica/Views/Cronograma/Delete.cshtml
@model HistClinica.DTO.CronogramaDTO
<div class="modal-dialog modal-md" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h2 class="modal-title text-center" id="exampleModalLabel1">¡Aviso!</h2>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@using (Html.BeginForm())
		{
			<div class="container">
				<div class="col-sm-12 pt-2 pb-3">
					¿Esta seguro que desea eliminar el Cronograma?
				</div>
				<div class="col-sm-12 pb-3">
					<div class="row">
						<div class="col-sm-6 text-center">
							@Html.HiddenFor(m => m.idProgramMedica)
							<button style="width:100px;" asp-action="Delete" class="btn btn-success">Si</button>
						</div>
						<div class="col-sm-6 text-center">
							<button style="width:100px;" class="btn btn-primary">No</button>
						</div>  
					</div>
				</div>
			</div>
		}
	</div>
</div>

HistClinica/HistClinica/Views/Cronograma/Details.cshtml
@model HistClinica.DTO.CronogramaDTO
<div class="modal-dialog modal-md" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h5 class="modal-title text-center" id="exampleModalLabel">Actualizar cronograma</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@using (Html.BeginForm("Edit", "Cronograma"))
		{
			<div class="modal-body">
				<div class="col-sm-12">
					<div class="row pb-2">
						<div class="col-sm-6">
							@Html.HiddenFor(m => m.idProgramMedica)

							<div class="row">
								<div class="col-sm-4">
									<label>Medico</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idMedico, new SelectList(ViewBag.listamedicos, "idMedico", "nombres"), "Seleccione", new { @class = "form-control", @disabled="true"})
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Especialidad</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idEspecialidad, new SelectList(ViewBag.listaespecialidades, "idtab", "descripcion"), new { @class = "form-control", @disabled = "true" })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb-2">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Fecha Inicio</label>
								</div>
								<div class="col-sm-8">

									@Html.DisplayFor(m => m.fechaIni, new { htmlAttributes = new { @class = "form-control", @type = "Date" } })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Fecha Fin</label>
								</div>
								<div class="col-sm-8">

									@Html.DisplayFor(m => m.fechaFin, new { htmlAttributes = new { @class = "form-control", @type = "Date" } })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb-2">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Hora Inicio</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.hrInicio, new SelectList(ViewBag.listahoras), new { @class = "form-control", @disabled = "true" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Hora Fin</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.hrFin, new SelectList(ViewBag.listahoras), new { @class = "form-control", @disabled = "true" })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb-2">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Estado</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idEstado, new SelectList(ViewBag.lestado, "idtab", "descripcion"), new { @class = "form-control", @disabled = "true" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Consultorio</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idConsultorio, new SelectList(ViewBag.listaconsultorio, "idtab", "descripcion"), new { @class = "form-control", @disabled = "true" })
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button style="width: 80px;" type="submit" class="btn btn-primary">Guardar</button>
					<button style="width: 80px;" type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
			</div>
		}

	</div>
</div>

HistClinica/HistClinica/Views/Cronograma/Edit.cshtml
@model HistClinica.DTO.CronogramaDTO
<div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h5 class="modal-title text-center" id="exampleModalLabel">Actualizar cronograma</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@using (Html.BeginForm("Edit", "Cronograma", FormMethod.Post, new { @id = "frmeditarcronograma" }))
		{
			@Html.AntiForgeryToken()
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			<div class="modal-body">
				<div class="col-sm-12">
					<div class="row pb-2">
						<div class="col-sm-6">
							@Html.HiddenFor(m => m.idProgramMedica)

							<div class="row">
								<div class="col-sm-4">
									<label>Medico</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idMedico, new SelectList(ViewBag.listamedicos, "idMedico", "nombres"), "Seleccione", new { @class = "form-control" })
									@Html.ValidationMessageFor(model => model.idMedico, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Especialidad</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idEspecialidad, new SelectList(ViewBag.listaespecialidades, "idtab", "descripcion"), new { @class = "form-control" })
									@Html.ValidationMessageFor(model => model.idEspecialidad, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb-2">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Fecha Inicio</label>
								</div>
								<div class="col-sm-8">

									@Html.EditorFor(m => m.fechaIni, new { htmlAttributes = new { @class = "form-control", @type = "Date" } })
									@Html.ValidationMessageFor(model => model.fechaIni, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Fecha Fin</label>
								</div>
								<div class="col-sm-8">

									@Html.EditorFor(m => m.fechaFin, new { htmlAttributes = new { @class = "form-control", @type = "Date" } })
									@Html.ValidationMessageFor(model => model.fechaFin, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb-2">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Hora Inicio</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.hrInicio, new SelectList(ViewBag.listahoras), new { @class = "form-control" })
									@Html.ValidationMessageFor(model => model.hrInicio, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Hora Fin</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.hrFin, new SelectList(ViewBag.listahoras), new { @class = "form-control" })
									@Html.ValidationMessageFor(model => model.hrFin, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb-2">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Estado</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idEstado, new SelectList(ViewBag.lestado, "idtab", "descripcion"), new { @class = "form-control" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Consultorio</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idConsultorio, new SelectList(ViewBag.listaconsultorio, "idtab", "descripcion"), new { @class = "form-control" })
									@Html.ValidationMessageFor(model => model.idConsultorio, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button style="width: 80px;" type="submit" class="btn btn-primary">Guardar</button>
					<button style="width: 80px;" type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
				</div>
			</div>
		}

	</div>
</div>

HistClinica/HistClinica/Views/Cronograma/Filtro.cshtml
@model HistClinica.Models.D012_CRONOMEDICO

@using (Html.BeginForm("Filtro", "Cronograma"))
{
	<div class="row pb-2">
		<div class="col-sm-4">
			<div class="row">
				<div class="col-sm-4">
					<label>Medico</label>
				</div>
				<div class="col-sm-8">
					@Html.DropDownListFor(m => m.idMedico, new SelectList(ViewBag.listamedicos, "idMedico", "nombres"), "Seleccione", new { @class = "form-control" })
				</div>
			</div>
		</div>
		<div class="col-sm-4">
		</div>
		<div class="col-sm-4">
			<button type="submit" class="btn btn-primary">Buscar</button>
		</div>
	</div>
}

HistClinica/HistClinica/Views/Cronograma/Index.cshtml
@model IEnumerable<HistClinica.DTO.CronogramaDTO>
@{
	ViewData["Title"] = "Index";
}

<div class="container">
	<div class="col-sm-12">
		<div class="row">
			<div class="col-sm-12 pt-2 pb-3">
				<h2>Horario de Medicos</h2>
			</div>
		</div>


		<partial name="Create" model="new HistClinica.Models.D012_CRONOMEDICO()">

			@if (ViewBag.message != null)
			{
				<div class="col-sm-12 alert alert-info alert-dismissible text-center" id="success-alert" role="alert" style="margin-top: 15px;">
					<button type="button" class="close" data-dismiss="alert" aria-label="close">
						<span aria-hidden="true">&times;</span>
					</button>
					@ViewBag.message
				</div>
			}

			<div class="row pt-3">
				<div class="col-sm-12">
					<table class="table table-bordered table-hover text-center" id="cronogramagrid">
						<thead>
							<tr>
								<th>Id</th>
								<th>Fecha Ini</th>
								<th>Fecha Fin</th>
								<th>Hora ini</th>
								<th>Hora fin</th>
								<th>Estado</th>
								<th>Acciones</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									<td>@item.idProgramMedica</td>
									<td>@item.fechaIni</td>
									<td>@item.fechaFin</td>
									<td>@item.hrInicio</td>
									<td>@item.hrFin</td>
									<td>@item.desEstado</td>
									<td>
										<button type="submit" class="edit btn btn-primary"><i class="fas fa-edit"></i></button>
										<button type="submit" class="delete btn btn-danger"><i class="fas fa-minus"></i></button>
									</td>
								</tr>
							}
						</tbody>
					</table>
				</div>
			</div>
	</div>
</div>

<div class="modal fade" id="modaldeletecrono" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>
<script src="~/js/cargavistaparcial.js"></script>
@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}