HistClinica/HistClinica/Controllers/CitaController.cs
using HistClinica.Data;
using HistClinica.DTO;
using HistClinica.Models;
using HistClinica.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace HistClinica.Controllers
{
    public class CitaController : Controller
    {
        private readonly IPacienteRepository _pacienteRepository;
        private readonly ClinicaServiceContext _context;
        private readonly ICitaRepository _repository;
        private readonly IUtilRepository _utilrepository;

        public CitaController(ClinicaServiceContext clinicaService,ICitaRepository repository, IUtilRepository utilRepository, IPacienteRepository pacienterepository)
        {
            _repository = repository;
            _context = clinicaService;
            _utilrepository = utilRepository;
            _pacienteRepository = pacienterepository;
        }

        // GET: Cita
        public async Task<IActionResult> Index()
        {
            return View(await _repository.GetAllCitas());
        }

        // GET: Cita/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var t068_CITA = await _repository.GetById(id);
            if (t068_CITA == null)
            {
                return NotFound();
            }

            return PartialView(t068_CITA);
        }



        // GET: Cita/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cita/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CitaDTO Cita)
        {
            if (Cita != null)
            {
                await _repository.InsertCita(Cita);
                return RedirectToAction(nameof(Index));
            }
            return View(Cita);
        }

        // GET: Cita/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lespecialidads = new Object();
            lespecialidads = await _utilrepository.GetTipo("Especialidad");
            ViewBag.listaespecialidades = lespecialidads;

            var medico = await _utilrepository.GetMedicos();
            ViewBag.listamedicos = medico;

            var lcronograma = await _utilrepository.GetCronograma();
            ViewBag.lcronograma = lcronograma;

            var lhoras = _utilrepository.GetHoras();
            ViewBag.lhoras = lhoras;

            var lestado = await _utilrepository.getEstadoCita();
            ViewBag.lestado = lestado;

            var servicios = await _utilrepository.GetTipo("Servicio Clinica");
            ViewBag.servicios = servicios;

            var t068_CITA = await _repository.GetById(id);
            if (t068_CITA == null)
            {
                return NotFound();
            }
            return PartialView(t068_CITA);

        }

        // POST: Cita/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CitaDTO cita)
        {
            if (cita.idCita != 0)
            {
                try
                {
                    TempData["dni"] = cita.dniPaciente;
                   TempData["mensajecita"] = await _repository.ReprogramarCita(cita);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _repository.CitaExists(cita.idCita))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index","Paciente");
            }
            return View();
        }

        // GET: Cita/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var t068_CITA = await _repository.GetById(id);
            if (t068_CITA == null)
            {
                return NotFound();
            }

            return View(t068_CITA);
        }

        public async Task<JsonResult> BuscarDni(int dni)
        {
            var personaDTO = await _pacienteRepository.GetByDnioNombresyApellidos(dni,"","");
            return Json(personaDTO);
        }

        // POST: Cita/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _repository.DeleteCita(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<JsonResult> GetMedicoByEsp(int id)
        {
            var medico = await _utilrepository.GetMedicoByEspecialidad(id);
            return Json(medico);
        }

        public async Task<JsonResult> GetCronogramaByMedico(int id)
        {
            var cronograma = await _utilrepository.GetCronogramaByMedico(id);
            return Json(cronograma);
        }

        public async Task<JsonResult> GetHorasByCronograma(int id)
        {
            var horas = await _utilrepository.GetHorasByCronograma(id);
            return Json(horas);
        }

        public async Task<IActionResult> Registro(int dni)
        {
            var lespecialidads = new Object();
            lespecialidads = await _utilrepository.GetTipo("Especialidad");
            ViewBag.listaespecialidades = lespecialidads;

            var medico = await _utilrepository.GetMedicos();
            ViewBag.listamedicos = medico;

            var lcronograma = await _utilrepository.GetCronograma();
            ViewBag.lcronograma = lcronograma;

            var servicios = await _utilrepository.GetTipo("Servicio Clinica");
            ViewBag.servicios = servicios;

            var lhoras = _utilrepository.GetHoras();
            ViewBag.lhoras = lhoras;

            CitaDTO cita = new CitaDTO();

            if (dni != 0)
            {
                PersonaDTO persona = await _pacienteRepository.GetByDnioNombresyApellidos(dni,"","");
                cita.dniPaciente = persona.numeroDocumento;
                cita.nombrePaciente = persona.nombres + ' ' + persona.apellidoPaterno + ' ' + persona.apellidoMaterno;
                cita.idPaciente = persona.paciente.idPaciente;
            }
            return PartialView(cita);
        }

        [HttpPost]
        public async Task<IActionResult> Registro(CitaDTO cita,string dni)
        {
            if (cita != null)
            {
                TempData["dni"] = dni;
                   TempData["mensajecita"] = await _repository.InsertCita(cita);
                return RedirectToAction("Index","Paciente");
            }
            return View(cita);
        }


        public async Task<IActionResult> AnularCita(int id)
        {
            var t068_CITA = await _repository.GetById(id);
            if (t068_CITA == null)
            {
                return NotFound();
            }
            return PartialView(t068_CITA);
        }
        [HttpPost]
        public async Task<IActionResult> AnularCita(CitaDTO cita)
        {
            TempData["dni"] = cita.dniPaciente;
            TempData["mensajecita"] = await _repository.AnularCita(cita.idCita, cita.motivoanulacion);
            return RedirectToAction("Index", "Paciente");
        }

        public async Task<IActionResult> CambiarEstadoCita(int id)
        {
            var estado = await _utilrepository.getEstadoCita();
            ViewBag.estado = estado;
            CitaDTO cita = await _repository.GetById(id);
            return PartialView(cita);
        }

        [HttpPost]
        public async Task<IActionResult> CambiarEstadoCita(CitaDTO cita)
        {
            TempData["msjcita"] = await _repository.CambiarEstadoCita(cita);
            return RedirectToAction("AdmicionMedico", "Paciente");
        }
    }
}

HistClinica/HistClinica/Views/Cita/Anular.cshtml
	<div class="modal-dialog modal-md" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title text-center" id="exampleModalLabel1">"¡Aviso!</h2>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="container">
				<div class="col-sm-12 pt-2">
					¿Esta seguro que desea anular la cita?
				</div>
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-6">
							<button class="btn btn-success">Si</button>
						</div>
						<div class="col-sm-6">
							<button class="btn btn-primary">No</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

HistClinica/HistClinica/Views/Cita/AnularCita.cshtml
@model HistClinica.DTO.CitaDTO	
<div class="modal-dialog modal-md" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h2 class="modal-title text-center" id="exampleModalLabel1">¡Aviso!</h2>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@using (Html.BeginForm())
		{
			<div class="container">
				<div class="col-sm-12 pt-2 pb-3">
					¿Esta seguro que desea anular la cita?
				</div>
				<div class="col-sm-12 pt-2 pb-3">
					<label>Motivo</label>
					@Html.TextAreaFor(m => m.motivoanulacion, new { @class = "form-control",  @style="width:356px" })
				</div>
				<div class="col-sm-12 pb-3">
					<div class="row">
						<div class="col-sm-6 text-center">
							@Html.HiddenFor(m => m.idCita)
							@Html.HiddenFor(m => m.dniPaciente)
							<button style="width:100px;" asp-action="AnularCita" class="btn btn-success">Si</button>
						</div>
						<div class="col-sm-6 text-center">
							<button style="width:100px;" class="btn btn-primary">No</button>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
	</div>

HistClinica/HistClinica/Views/Cita/CambiarEstadoCita.cshtml
@model HistClinica.DTO.CitaDTO
<div class="modal-dialog modal-md" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h2 class="modal-title text-center" id="exampleModalLabel1">¡Aviso!</h2>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@using (Html.BeginForm())
		{
			<div class="container">
				<div class="col-sm-12 pt-2 pb-3">
					¿Esta seguro que desea cambiar el estado de la cita?
				</div>
				<div class="col-sm-12 pt-2 pb-3">
					<label>Motivo</label>
					@Html.DropDownListFor(m => m.estado, new SelectList(ViewBag.estado, "idEstadoCita", "estado"), "Seleccione", new { @class = "form-control" })
				</div>
				<div class="col-sm-12 pb-3">
					<div class="row">
						<div class="col-sm-6 text-center">
							@Html.HiddenFor(m => m.idCita)
							<button style="width:100px;" asp-action="CambiarEstadoCita" class="btn btn-success">Si</button>
						</div>
						<div class="col-sm-6 text-center">
							<a style="width:100px;" class="btn btn-primary" data-dismiss="modal">No</a>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>

HistClinica/HistClinica/Views/Cita/Delete.cshtml
@*@model HistClinica.Models.T068_CITA

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>T068_CITA</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.codCita)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.codCita)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nroCita)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nroCita)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fechaCita)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fechaCita)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ultCie10)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ultCie10)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.servicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.servicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tpAtencion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tpAtencion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nroHC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nroHC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idEstadoCita)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idEstadoCita)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idEstaGralPac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idEstaGralPac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estadoReprogram)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estadoReprogram)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ejecutado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ejecutado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prioridad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prioridad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descuento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descuento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.coa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.coa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.igv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.igv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idPaciente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idPaciente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idConsultorio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idConsultorio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idProgramMedica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idProgramMedica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idTpAtencion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idTpAtencion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idEstAtencion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idEstAtencion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="idCita" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>*@

HistClinica/HistClinica/Views/Cita/Edit.cshtml
@model HistClinica.DTO.CitaDTO
<div class="modal-dialog" role="document">
	<div class="modal-content" style="width: 1200px;position: relative;right: 302px;">
		<div class="container">
			<div class="col-sm-12 pb-2 pt-3 pb-2">
				<h4>Reprogramacion de cita ambulatoria</h4>
			</div>
			@using (Html.BeginForm(FormMethod.Post, new { @id = "frmeditcita" }))
			{
				@Html.AntiForgeryToken()
				@Html.ValidationSummary(true, "", new { @class = "text-danger" })
				<div class="col-sm-12">
					<div class="row pb-3">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Id Cita</label>
								</div>
								<div class="col-sm-8">
									@Html.HiddenFor(m => m.idCita)
									@Html.EditorFor(m => m.idCita, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
						</div>
					</div>
					<div class="row pb-3">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Especialidad</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idEspecialidad, new SelectList(ViewBag.listaespecialidades, "idtab", "descripcion"), "Seleccione", new
									{
										@class = "form-control",
								   data_cascade_combo = "#medico",
								   data_cascade_combo_source = Url.Action("GetMedicoByEsp", "Cita"),
								   data_cascade_combo_param_name = "id"
							   })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Medico</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idmedico, new SelectList(ViewBag.listamedicos, "idMedico", "nombres"), "Seleccione", new
									{
										@class = "form-control",
										@id = "medico",
								   data_cascade_combo_medico = "#fecate",
								   data_cascade_combo_source_medico = Url.Action("GetCronogramaByMedico", "Cita"),
								   data_cascade_combo_param_name_medico = "id"
							   })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Fecha Atencion</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idProgramMedica, new SelectList(ViewBag.lcronograma, "idprogramMed", "fecprogram"), "Seleccione", new
							   {
								   @class = "form-control",
								   data_cascade_combofec = "#horaate",
								   data_cascade_combo_sourcefec = Url.Action("GetHorasByCronograma", "Cita"),
								   data_cascade_combo_param_namefec = "id",
								   @id = "fecate"
							   })
									@Html.ValidationMessageFor(model => model.idProgramMedica, "", new { @class = "text-danger" })
								</div>
								<input type="hidden" id="desfecha" asp-for="fecha" />
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Hora</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownList("horaate", new SelectList(ViewBag.lhoras, "id", "hora"), "Seleccione", new { @class = "form-control", @id = "horaate" })
								</div>
								<input type="hidden" id="deshora" asp-for="hora" />
							</div>
						</div>
						<div class="col-sm-4"></div>
					</div>
					<div class="row pb-3 pt-3">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Dni</label>
								</div>
								<div class="col-sm-8 form-inline">
									@Html.EditorFor(m => m.dniPaciente, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
									@Html.HiddenFor(m => m.dniPaciente)
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Paciente</label>
								</div>
								<div class="col-sm-8">
									<input type="hidden" class="form-control pr-2" id="idpaciente">
									<input type="text" class="form-control pr-2" id="nombrepaciente" asp-for="nombrePaciente" name="" disabled>
								</div>
							</div>
						</div>
					</div>
					<div class="row pb-3 pt-3">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Servicios</label>
								</div>
								<div class="col-sm-8 form-inline">
									@Html.DropDownListFor(m => m.idServicioCli, new SelectList(ViewBag.servicios, "idtab", "descripcion"), "Seleccione", new { @class = "form-control", @disabled="true" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">

						</div>
					</div>
					<div class="row pt-3">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Motivo</label>
								</div>
								<div class="col-sm-8 form-inline">
									@Html.TextAreaFor(m => m.motivoreprogramacion, new { @class = "form-control", @style = "width:365px" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">

						</div>
					</div>
					<div class="row pt-3 pb-2">
						<div class="col-sm-12 text-right">
							<button class="btn btn-primary">Registrar</button>
						</div>
					</div>
				</div>
			}
		</div>
	</div>
</div>

HistClinica/HistClinica/Views/Cita/Registro.cshtml
@model HistClinica.DTO.CitaDTO
<div class="modal-dialog" role="document">
	<div class="modal-content" style="width: 1200px;position: relative;right: 302px;">
		<div class="container">
			<div class="col-sm-12 pb-2 pt-3">
				<h4>Programacion de cita ambulatoria</h4>
			</div>
			@using (Html.BeginForm(FormMethod.Post, new { @id = "frmregistrarcita" }))
			{
				@Html.AntiForgeryToken()
				@Html.ValidationSummary(true, "", new { @class = "text-danger" })
				<div class="col-sm-12">
					<div class="row pb-3">
						<div class="col-sm-6">
							<div class="form-check form-check-inline">
								<input type="hidden" name="name" value="2" asp-for="idEmpleado" />
								@Html.RadioButtonFor(m => m.idTipoCita, 168, new { @class = "form-check-input", @checked = "true" })
								<label class="form-check-label" for="inlineRadio1">Consulta</label>
							</div>
							<div class="form-check form-check-inline">
								@Html.RadioButtonFor(m => m.idTipoCita, 170, new { @class = "form-check-input" })
								<label class="form-check-label" for="inlineRadio2">Procedimiento</label>
							</div>
							@Html.ValidationMessageFor(model => model.idTipoCita, "", new { @class = "text-danger" })
						</div>
						<div class="col-sm-6"></div>
					</div>
					<div class="row pb-3">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Especialidad</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownList("especialidad", new SelectList(ViewBag.listaespecialidades, "idtab", "descripcion"), "Seleccione", new
									{
										@class = "form-control",
								   data_cascade_combo = "#medico",
								   data_cascade_combo_source = Url.Action("GetMedicoByEsp", "Cita"),
								   data_cascade_combo_param_name = "id"
							   })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Medico</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idEmpleado, new SelectList(ViewBag.listamedicos, "idMedico", "nombres"), "Seleccione", new
									{
										@class = "form-control",
										@id = "medico",
								   data_cascade_combo_medico = "#fecate",
								   data_cascade_combo_source_medico = Url.Action("GetCronogramaByMedico", "Cita"),
								   data_cascade_combo_param_name_medico = "id"
							   })
									@Html.ValidationMessageFor(model => model.idEmpleado, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Fecha Atencion</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownListFor(m => m.idProgramMedica, new SelectList(ViewBag.lcronograma, "idprogramMed", "fecprogram"), "Seleccione", new
							   {
								   @class = "form-control",
								   data_cascade_combofec = "#horaate",
								   data_cascade_combo_sourcefec = Url.Action("GetHorasByCronograma", "Cita"),
								   data_cascade_combo_param_namefec = "id",
								   @id = "fecate"
							   })
									@Html.ValidationMessageFor(model => model.idProgramMedica, "", new { @class = "text-danger" })
								</div>
								<input type="hidden" id="desfecha" asp-for="fecha" />
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Hora</label>
								</div>
								<div class="col-sm-8">
									@Html.DropDownList("horaate", new SelectList(ViewBag.lhoras, "id", "hora"), "Seleccione", new { @class = "form-control", id = "horaate" })
									<input type="hidden" id="deshora" asp-for="hora" />
									@Html.ValidationMessageFor(model => model.hora, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
						<div class="col-sm-4"></div>
					</div>
					<div class="row pb-3 pt-3">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Dni</label>
								</div>
								<div class="col-sm-8 form-inline">
									<input type="text" class="form-control pr-2" asp-for="dniPaciente">
									@if (Model.idPaciente == null)
									{
										<a onclick="BuscarPaciente();" class="btn btn-primary"><i style="color:white;" class="fas fa-search"></i></a>
									}
									@Html.ValidationMessageFor(model => model.dniPaciente, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Paciente</label>
								</div>
								<div class="col-sm-8">
									<input type="hidden" class="form-control pr-2" id="idpaciente" asp-for="idPaciente">
									<input type="text" class="form-control pr-2" id="nombrepaciente" asp-for="nombrePaciente">
									@Html.ValidationMessageFor(model => model.nombrePaciente, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
					</div>
					<div class="row pb-3 pt-3">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-4">
									<label>Servicios</label>
								</div>
								<div class="col-sm-8 form-inline">
									@Html.DropDownListFor(m => m.idServicioCli, new SelectList(ViewBag.servicios, "idtab", "descripcion"), "Seleccione", new { @class = "form-control" })
									@Html.ValidationMessageFor(model => model.idServicioCli, "", new { @class = "text-danger" })
								</div>
							</div>
						</div>
						<div class="col-sm-6">

						</div>
					</div>
					<div class="row pt-3 pb-2">
						<div class="col-sm-12 text-right">
							<button class="btn btn-primary">Registrar</button>
						</div>
					</div>
				</div>
			}
		</div>
	</div>
</div>